trigger:
- main

jobs:
- job: Publish

  pool:
    vmImage: ubuntu-latest

  variables:
  - group: secrets

  steps:
  
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '>=16.18.0'
  
  - task: Npm@1
    inputs:
      command: install
  
  - pwsh: |
      # get namespace
      $null = npx wrangler kv:namespace create KV_DOMAIN
      $ns = npx wrangler kv:namespace list | ConvertFrom-Json | Where-Object title -match 'KV_DOMAIN'
      if ($null -eq $ns) {
        throw
      }
      ConvertTo-Json -Compress $ns

      # create KV binding
      echo "[env.production]" >> wrangler.toml
      $binding = "kv_namespaces = [{binding=`"KV_DOMAIN`", id=`"$($ns.id)`"}]"
      $binding
      echo $binding >> wrangler.toml
      
      # create routes for each domain in KV
      $routes = @()
      $domains = npx wrangler kv:key list --namespace-id $ns.id
      $domains
      $domains = ($domains | ConvertFrom-Json).name
      $domains
      echo "routes = [" >> wrangler.toml
      for ($i=0; $i -lt $domains.Count; $i++) {
        $route = "  { custom_domain = true, pattern = `"mta-sts.$domain`", zone_name = `"$domain`" },"
        if ($i -eq $domains.Count - 1) {
          # remove trailing comma
          $route = $route -replace '.$'
        }
        echo $route >> wrangler.toml
      }
      echo "]" >> wrangler.toml

      # wrangler publish
      cat wrangler.toml
    env:
      CLOUDFLARE_ACCOUNT_ID: $(AccountId)
      CLOUDFLARE_API_TOKEN: $(ApiToken)
